framework:
    enabled_locales: ['pt_BR', 'py']
    default_locale: pt_BR
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - py
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
